### ISSUE TITLE
Fix POSIX syntax

### ISSUE THREAD

**Issue by RafaelAybar** [mautic/docker-mautic#122]
Hi, i was editing de docker-entrypoint.sh script and when I ran [shellcheck](https://github.com/koalaman/shellcheck) i saw this warning:

![imagen](https://user-images.githubusercontent.com/21227176/62855369-5e32b600-bcf2-11e9-8129-39f1cfa57cac.png)
Here you are the docs that i have read to solve  it, also i will send a PR with the fix.
https://github.com/koalaman/shellcheck/wiki/SC2166

**Comment by luizeof** [comment]
many thanks @RafaelAybar !!!
