### ISSUE TITLE
Error : net::ERR_TOO_MANY_REDIRECTS when clear cache

### ISSUE THREAD

**Issue by nguyencongvu** [mautic/docker-mautic#129]
I install mautic docker successfully in my ubuntu VPS, and enable API in Configuration. 
However, I got error net::ERR_TOO_MANY_REDIRECTS any time clear cache (by rm -rf /app/cache or run php consol 
Any help?

**Comment by luizeof** [comment]
did you use some reverse proxy?

**Comment by pxPP** [comment]
same problem since I changed the URL in the settings to https ...

**Comment by luizeof** [comment]
@pxPP  did you use some reverse proxy?

**Comment by luizeof** [comment]
if you are using some reverse proxy, you need to add a trusted proxy to your 'local.php' config
