### ISSUE TITLE
Upgrade to mautic 2.15.2 ?

### ISSUE THREAD

**Issue by robov** [mautic/docker-mautic#131]
Upgrade to mautic 2.15.2 ?

**Comment by soundzgoood** [comment]
Hi everyone, it seems like mautic is updated to 1.15.2 in the git repository but still on 1.15.1 on docker hub https://hub.docker.com/r/mautic/mautic/dockerfile
Would be super happy to have the official dockerfiles also updated for download.
Thanks a lot!

**Comment by StoppingBuck** [comment]
I was the one who created the issue to get the docker image to upgrade from 2.15.0 to 2.15.1. I think we need a more stable procedure for this stuff. Right now, the docker image always seems obsolete :/

**Comment by robov** [comment]
There is also an upgrade script to run it yourself. Just run the script inside the container

**Comment by robov** [comment]
I am still testing out mautic, so my db is clean and I have no plugins. Upgrading worked, but the migration step was extremely slow...(I have not dived in what happend there)

**Comment by RCheesley** [comment]
Closing this issue as we're now on 2.16.1 so it's somewhat irrelevant :)
