### ISSUE TITLE
Issue with deployment 

### ISSUE THREAD

**Issue by elitekode2** [mautic/docker-mautic#145]
Trying to deploy via docker.. 

Getting issue 

`5.7.28-31�=��T#ysDfC�ÿÿ-�ÿÁ����������O<2r/dpK(|�mysql_native_password���ÿ„Got packets out of order`

and 

`
MySQL Connection Error: (2002) Connection refused

Warning: mysqli::__construct(): (HY000/2002): Connection refused in /makedb.php on line 20

Ensuring Mautic database is present
`

**Comment by luizeof** [comment]
I am closing this issue because it is old, but if you still encounter problems could you reopen informing how is compose.yml?
