### ISSUE TITLE
Missing ZipArchive class

### ISSUE THREAD

**Issue by grzana12** [mautic/docker-mautic#15]
I couldn't change language in error logs line:

> mautic.ERROR: Fatal: Class 'ZipArchive' not found - in file /var/www/html/app/bundles/CoreBundle/Helper/LanguageHelper.php - at line 77 [] []

In dockerfile sholud be one more PHP ext installed:
`docker-php-ext-install zip`

**Comment by Gregy** [comment]
Thank you for the bug report. Sorry it took so long. Zip extension is included in the latest container.
