### ISSUE TITLE
Not able to access http://localhost:8080 or http://host-ip:8080 to test out Mautic

### ISSUE THREAD

**Issue by jenshine** [mautic/docker-mautic#161]
Hi there! 
I followed the instructions on http://hub.docker.com/r/mautic/mautic to test out Mautic using a docker container I created through a droplet on DigitalOcean. All these technologies are new for me (as in I'm just trying it for the first time today). I'm not exactly sure where it's breaking. 

When I execute 'docker-compose up', it looks like everything worked despite some error messages . When I do a 'docker ps', I do see the mautic and the mauticdb containers. However, when I tried going to http://localhost:8080 or http://100.115.92.197:8080/ (host IP of my Chromebook), nothing is returning. I get "ERR_EMPTY_RESPONSE" when I go to http://localhost:8080. http://100.115.92.197:8080/ times out. 

1) What should I be seeing if everything were successful (just curious)? 
2) Is there any other way to confirm that mautic and the mauticdb are set up and running as expected? Does seeing them listed under 'docker ps' signify that they are running correctly? 
3) Assuming everything looks ok from the docker side, perhaps the issue is then specific to a Chromebook development environment. Does anyone know what needs to be done in this case? Is there anything I should change in the docker-compose.yml that might fix the issue I'm encountering? 

Thank you so much. 

![Screenshot 2020-05-01 at 6 36 10 PM](https://user-images.githubusercontent.com/425569/80800049-11be3c00-8bdb-11ea-90c5-33c860d0d49b.png)
![Screenshot 2020-05-01 at 6 38 37 PM](https://user-images.githubusercontent.com/425569/80800058-15ea5980-8bdb-11ea-9620-ea1ef49d8ec8.png)
![Screenshot 2020-05-01 at 6 36 33 PM](https://user-images.githubusercontent.com/425569/80800062-1a167700-8bdb-11ea-88da-038dbb1346dc.png)

**Comment by jenshine** [comment]
Figured it out!

**Comment by rodrigoscna** [comment]
> Figured it out!

@jenshine What did you do to solve it?

**Comment by jenshine** [comment]
> > Figured it out!
> 
> @jenshine What did you do to solve it?

Wow, sorry, I'm just seeing this question today. Based on what I had posted, it's very likely I was trying to access Mautic via my local IP instead of the virtual server (Digital Ocean droplet) IP.

**Comment by jenshine** [comment]
> > Figured it out!
> 
> @jenshine What did you do to solve it?
