### ISSUE TITLE
Language not working properly

### ISSUE THREAD

**Issue by rucksman** [mautic/docker-mautic#162]
After 3 years I again started to work with Mautic and currently run this docker container.

When changing the account configuration to language "German", although the language files are downloaded, I still get only english. There is also no language change when changing the system default language.
When changing the account configuration to language "Italian", language files are downloaded and the page is immediately converted to show it in the italian version.
Why do I have these problems with German? I already logged out and in again a few times, but when changing th German, only the english version is shown.

**Comment by alexhammerschmied** [comment]
You have to clear the cache. Then reload the page and voila! It should work.

**Comment by PhilippeAccorsi** [comment]
I have clean all cache in my Firefox 68.9.0esr (64 bits), and nothing change. Interface stay in English.
I have check and French language is download correctly (file available in docker volume), but interface stay in english.

Same with Chrome 83.0.4103.97

I'm on Debian Buster.

**Comment by alexhammerschmied** [comment]
You have to clear the cache on your Mautic instance. This has nothing to do with your browser. 
Just clear everything inside the cache folder in mautic somewhere here:  ../mautic/app/cache/*

Also see: [https://docs.mautic.org/en/troubleshooting]

**Comment by rucksman** [comment]
Deleting the cache worked for me.
