### ISSUE TITLE
Reverse Proxy HTTPS for Form Generation embedded on third party site

### ISSUE THREAD

**Issue by alderson59** [mautic/docker-mautic#185]
So far, there is no way to update Docker Mautic to v3.2, at least not in a stable way that I know how to.
https://github.com/mautic/mautic/issues/9567

I also note that in 3.1, HTTPS behind reverse proxy support was added.
https://github.com/mautic/mautic/issues/8944 
https://github.com/mautic/mautic/issues/9499

Since I am now stuck with v3.0.2, here's what I have tried:
1. Added `$_SERVER['HTTPS'] = 'on';` to `index.php` (referring to https://github.com/mautic/docker-mautic/issues/20#issuecomment-499871661)
2. `rm -r var/cache`, to clear cache
3. docker compose down and up, just to clear things.
4. Open the site where the mautic form was embedded, console shows:
![Untitled-1](https://user-images.githubusercontent.com/69715968/103907356-24aae800-513c-11eb-851f-bb5b4d8d7995.jpg)
![image](https://user-images.githubusercontent.com/69715968/103907270-093fdd00-513c-11eb-9ea3-5b3f4929485f.png)

**Additional info:**
docker image: mautic:v3 (so it's apache)
reverse proxy: https://github.com/jc21/nginx-proxy-manager

- I have added trusted hosts and trusted proxies.
- I tried changing the mautic base URL in the web config (or app/config/local.php), to add https:// to the URL, it just redirects in an infinite loop, so this was not viable.
- Am not a pro dev, so not too deeply versed in code.

**References:**
#20
https://github.com/mautic/mautic/issues/7577 
https://github.com/mautic/mautic/issues/7931 
https://github.com/mautic/mautic/issues/7588 

What can I do here to temporarily fix this https issue? 

Or what can I do to get the latest version of mautic via docker, in a stable way?

**Comment by alderson59** [comment]
UPDATE: referencing mautic/mautic#8944 and mautic/mautic#9499, mautic/mautic#9567, I managed to get my install to v3.2.2, which **should** have reverse proxy support for https.

As best as I could follow, I have added the trusted reverse proxy host and the trusted host to the web config.

I could not change the site URL to https without causing looping redirects.

The embedded form on a third party website doesn't load via HTTPS even though the Mautic install is terminated by SSL behind a reverse proxy.

Any help here? Thanks

**Comment by alderson59** [comment]
Ahh, I finally figured it out - had to do this "If you change the Site Address of Mautic General Settings tab to HTTPS (behind a reverse proxy), you can use 0.0.0.0/0 as Trusted Proxies to avoid a redirect loop error. See documentation" - from dockerhub page. https://hub.docker.com/r/mautic/mautic

**Comment by valerio-bozzolan** [comment]
I just want to mention that Symfony seems to need an additional configuration in order to trust the header `X-Forwarded-Proto` - so - to understand that it's under a reverse proxy. Documentation:

https://symfony.com/doc/current/deployment/proxies.html

Example PHP:

```
// config/packages/framework.php
use Symfony\Config\FrameworkConfig;

return static function (FrameworkConfig $framework) {
    $framework
        // the IP address (or range) of your proxy
        ->trustedProxies('192.0.0.1,10.0.0.0/8')
        // trust *all* "X-Forwarded-*" headers (the ! prefix means to not trust those headers)
        ->trustedHeaders(['x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto', 'x-forwarded-port', 'x-forwarded-prefix'])
        // or, if your proxy instead uses the "Forwarded" header
        ->trustedHeaders(['forwarded'])
    ;
};
```

I just mention this fact here since I don't know if this is causing problems right now or could cause this in the future.

**Comment by riosje** [comment]
If some one face this issue using php-fpm + nginx you can set this param `fastcgi_param HTTPS "on"; ` in my case was in nginx.
I know nothing about php, but this solved the issue for me.
I'm using the docker version
> implementation https://github.com/mautic/docker-mautic/tree/mautic5/examples/fpm-nginx
