### ISSUE TITLE
How can one specify cron intervals

### ISSUE THREAD

**Issue by TimPchelintsev** [mautic/docker-mautic#19]
Hi. Thanks for amazing work! I wonder what is the way to customise cron jobs(want to speed up things a bit, say process events every min, not 15 mins). I see that I can switch it off completely, then how should I provide this functionality from my side? It will be cool if we can somehow provide file with cron settings to the container.. I am quite new to docker(and cron too), sorry if it's obvious:)

**Comment by Gregy** [comment]
Hi, you need to replace crontab file (https://github.com/mautic/docker-mautic/blob/master/common/mautic.crontab) with your own version.

**Comment by xtjoeywx** [comment]
Hi Gregy and TimPchelintsev, I'm new to docker and cron as well and I'm trying to find the mautic.crontab file on my server.

I'm using Ubuntu and I don't see it in here: /var/spool/cron/crontabs

I also don't see it here either:
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

Would either of you kindly tell me where I can find the file so I can replace it?

**Comment by xtjoeywx** [comment]
I found two files called "mautic" by using this search command: `find / -type f -iname "mautic"`

The contents of both match the mautic.crontab file you mentioned above. They are located in different locations of each other. I didn't expect there to be two files in two different locations, therefore, I'm not sure which one to change. Do I need to change both of them or just one of them?

One is located here:
/var/lib/docker/overlay2/A VERY LONG STING OF NUMBERS/diff/etc/cron.d/mautic

...and the other is located here:
/var/lib/docker/overlay2/A VERY LONG STRING OF NUMBERS/merged/etc/cron.d/mautic
