### ISSUE TITLE
Consider switching to GitHub Actions for automated Docker Hub builds

### ISSUE THREAD

**Issue by dennisameling** [mautic/docker-mautic#206]
As discussed in Slack (https://mautic.slack.com/archives/C0DMR1DRS/p1628762987006700), Docker has a paid [Automated Builds](https://docs.docker.com/docker-hub/builds/) feature. In the past something was set up by @luizeof but I'm not sure if that was leveraging this feature or something different:

![image](https://user-images.githubusercontent.com/17739158/129588451-f61250ba-08ef-43cf-82e3-5db8fecf21bf.png)

As suggested by @RCheesley, it is possible to use GitHub Actions for pushing builds to Docker Hub (see [this article](https://snyk.io/blog/how-to-publish-node-js-docker-images-to-docker-hub-registry-using-github-actions/)). I'm happy to set that up, but first will need some info on the existing integration before I can move forward. Otherwise I might potentially break the existing integration or cause duplicate builds.

Required actions if we want to move to GH Actions:

- [ ] Get feedback from @luizeof on existing integration and how we can turn that off
- [x] Have @RCheesley be the account owner for Mautic Docker Hub and share credentials with me that GH Actions can use
- [ ] Me setting up the actual pipeline 😉

**Comment by RCheesley** [comment]
I have access to DockerHub so I can sort out that side of it! Over to you @luizeof!

**Comment by mollux** [comment]
closing this issue as this was implemented in #238
