### ISSUE TITLE
images for 3.3.4 and 4.0.0 not yet on hub.docker.com

### ISSUE THREAD

**Issue by GuidoDr** [mautic/docker-mautic#209]
3.3.4 and 4.0.0 have been released two days ago and our mautic 3.3.3 version is showing that an upgrade is available.
But there are not yet docker images for these versions on hub.docker.com .
When will the new releases be available as docker images?

**Comment by Kovah** [comment]
The tags seem to be a total mess. The `latest` tag is more than a year old.
The `v3` tag is dating back to april, but there is a `v4` tag that seems to contain v4.0.0.

**Comment by RCheesley** [comment]
Waiting on @luizeof to get these deployed. Can we get an update please?

**Comment by Kovah** [comment]
Let me know if you need help with Docker and CI pipelines. :)

**Comment by RCheesley** [comment]
@Kovah perhaps you could join #docker on Slack (https://mautic.org/slack to get an invite) - we're definitely keen to have more contributors helping us to manage our Docker workflows :)

**Comment by AWessel77** [comment]
If you are deploying anyway maybe you could also fix the `v4` image because the version behind the `v4` tag is "just" `4.0.0-rc`.
https://hub.docker.com/layers/mautic/mautic/v4/images/sha256-33db36813c8469eff11f10214feac580f98dea39a388b97dccf9e63f42083f69?context=explore Line 40

**Comment by luizeof** [comment]
@AWessel77  I'm updating the image to the final version today .... @Kovah it would be great for someone to collaborate with Mautic Docker, we have a lot of work testing pull #198

**Comment by luizeof** [comment]
@AWessel77  always remember that the variable MAUTIC_VERSION can be used for you to specify the desired version ;)

**Comment by AWessel77** [comment]
@luizeof I knew that, but thanks anyway for the tip. I was just surprised about the rc version label in the frontend as I worked with the v4 image.

**Comment by RCheesley** [comment]
Awesome, thanks @luizeof ! 🚀
