### ISSUE TITLE
Redirect Problem on AWS ECS with API Gateway

### ISSUE THREAD

**Issue by giroto** [mautic/docker-mautic#210]
We are running the 4.0 image on ECS Fargate and using API Gateway with a domain and SSL certificate.
All system works fine but some times, mautic change HTTPS to HTTP. On site URL inside configurations, we are using the domain with HTTPS.
Im trying to investigate furthermore inside .htaccess but until now I got nothing.

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)
