### ISSUE TITLE
Permissions Errors at Install in Mautic 4.0

### ISSUE THREAD

**Issue by user592965** [mautic/docker-mautic#211]
Hello, The last docker image mautic/mautic:v4 can't start (fatal error) because of group writable permissions for files:
/etc/sudoers
/usr/lib/sudo/sudoers.so

linux: ubuntu 20.04 lts
docker-ce: 20.10.8

Mapping the volumes and change the permissions of these files with "chmod 644" (instead of 674 at the origin) solved the issue. But it happens again at each system prune.

**Comment by luizeof** [comment]
I cannot reproduce this issue. Here when installed in a VPA with docker-ce 20+ on Debian using volumes, it works fine.

**Comment by user592965** [comment]
ok, maybe a problem on my side only then related to my setup. By using @iBobik stateless image I don't have this problem anymore.
