### ISSUE TITLE
How to change timezone to my local timezone

### ISSUE THREAD

**Issue by fav22** [mautic/docker-mautic#217]
Hello , hope you all doing well !

Anyone here know how to change timezone to my local timezone using php on ssh please ? 

I want to change the default timezone UTC to GMT +3 Indian/Antananarivo 

Thank you all for your hel^p

**Comment by astanoszek** [comment]
in your docker-compose.yml, section environment set:
- PHP_INI_DATE_TIMEZONE="timezone" 
where timezone is one of listed here: https://www.php.net/manual/en/timezones.indian.php

**Comment by fav22** [comment]
> in your docker-compose.yml, section environment set:
> 
> * PHP_INI_DATE_TIMEZONE="timezone"
>   where timezone is one of listed here: https://www.php.net/manual/en/timezones.indian.php

Hello , thank your reply ! I fix it ! 

My new problem is why all mail i sent through mautic goes to spam whereas when I send directly from my postal smtp server it falls directly in inbox?

**Comment by astanoszek** [comment]
I think that this issue should be discussed on https://forum.mautic.org/ as it is not about the bug in docker-mautic
