### ISSUE TITLE
Mautic does not support PHP version 7.0.21

### ISSUE THREAD

**Issue by yankees9920** [mautic/docker-mautic#22]
I just ran the container with the docker-compose file included and I received the following error.

`Mautic does not support PHP version 7.0.21 at this time. To use Mautic, you will need to downgrade to an earlier version.`

**Comment by Gregy** [comment]
I cannot replicate this. My guess is that you are using some old version of the docker image. Please post the version of mautic in the docker image. Current should be 2.9.0 (you can check the version by reading file /var/www/html/app/version.txt inside the container)
