### ISSUE TITLE
Mautic latest docker image is two years old

### ISSUE THREAD

**Issue by ramonchu** [mautic/docker-mautic#227]
### Mautic Version

4.2.x series

### PHP version

7.3.27

### What browsers are you seeing the problem on?

Not relevant

### What happened?

Docker latest image is obsolete.

[latest](https://hub.docker.com/layers/mautic/mautic/mautic/latest/images/sha256-1f90b3618469c96ec4df09c14535828543db2bd6475cde075ae08e0c9dd7cecd?context=explore)
docker pull mautic/mautic:latest
Last pushed 2 years ago by [mautic](https://hub.docker.com/u/mautic)

### How can we reproduce this issue?

Please, confirm navigating to page: https://hub.docker.com/r/mautic/mautic/tags

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by mcnaveen** [comment]
When I changed the mautic version from `latest` to `v4` the container keeps restarting.

**Comment by cyberfab007** [comment]
I can reproduce this, 


MySQL Database Created
========================================================================
This server is now configured to run Mautic!
The following information will be prefilled into the installer (keep password field empty):
Host Name: mauticdb
Database Name: mautic
Database Username: root
Database Password: Wng@5hQKu%tw5T7vls
========================================================================


========================================================================
Updating existing mautic config
========================================================================


Could not open input file: /var/www/html/bin/console

Then I found this :

https://stackoverflow.com/questions/34016449/could-not-open-input-file-bin-console-error-comes-when-try-to-run-the-symfony

this needs to be ran i think 

php app/console server:run

**Comment by vinyll** [comment]
The latest refers also to an old version while we are at v5 as release candidate.

**Comment by mollux** [comment]
@vinyll @cyberfab007 @ramonchu 

It's indeed correct that `latest` doesn't point to the last build of the Docker images for this repo, see also https://github.com/mautic/docker-mautic/tree/mautic4?tab=readme-ov-file#pulling-mautic-images-from-docker-hub

Regarless of the stale tag, for this repo (and many many others) It's not a good practice to depend on the `latest` tag for multiple reasons (a quick search on `docker latest tag` should give some pointers).
You should use at least an image pointing to the major version of Mautic, to ensure you're pulling the correct version.

Please see #238 that was recently merged, and https://hub.docker.com/r/mautic/mautic for the most recent images.

I'll create a separate issue to suggest to remove the `latest` tag, or have a better definition of where it should point to
