### ISSUE TITLE
Both v3 and v4 images are not starting

### ISSUE THREAD

**Issue by jensenhertz** [mautic/docker-mautic#232]
v3 fails with `[CRON] Could not open input file: /var/www/html/bin`

v4 fails with `Could not open input file: /var/www/html/bin/console`

Only thing that works is 2 years old v2.

I built the images from source also.

Please mark this repo deprecated since you are not keeping these updated.

**Comment by RCheesley** [comment]
@luizeof @wget can you provide any input here please? Thanks!

**Comment by jensenhertz** [comment]
I noticed there was an update to mautic:v4 like a week ago. Still fails with `Could not open input file: /var/www/html/bin/console` for me.

I assume there is some magic sauce involved to get these >v2 versions up and running, anyone know what it is?

**Comment by luizeof** [comment]
@jensenhertz are you running mautic 4? Just updating the container does not update Mautic.

**Comment by jensenhertz** [comment]
@luizeof Uf, amateur mistake: I took the previous docker-compose down without `-f`, so it didn't remove the volume.

I removed the volume and now it starts. Thanks!
