### ISSUE TITLE
Maintaining the official docker-mautic

### ISSUE THREAD

**Issue by francoisauclair911** [mautic/docker-mautic#240]
Hi,

I would like to know if some of you would be interested in creating a team of maintainers (official or not) do maintain the mautic-docker versions to be as close to possible as the non-dockerize?

Some roadmap items I have in mind

- Releasing minor fixes  quickly to the docker versions.
- Write clear documentation on
  - Initial deployment
  - Upgrading mautic 
  - Upgrading plugins (from a docker stateless perspective) 
- Work on achieving a stateless docker image by default ([see here](https://github.com/thinkl33t/docker-mautic/tree/mautic4-volumes))
- Automating CI/CD (github actions) to release new versions automatically
- Extracting some plugins to be mounted as separate docker images (side container)
- Creating an helm chart to support kubernetes deployment more easily

Let me know if some of you are interested in this

Francois

**Comment by luizeof** [comment]
@francoisauclair911 @RCheesley I fully support

**Comment by RCheesley** [comment]
@mollux @npracht @jos0405 for info!

**Comment by davidspiola** [comment]
I'm happy to contribute, but I'm not sure if I can do that on a regular basis. This is the image I have been working on so far, with a few quirks and features, but it would be even better to have an officially supported image :-)

https://github.com/Garagist/docker-mautic

**Comment by wget** [comment]
Count me in as well =) Have several Dockerized production instances running.

I'm mostly using Docker-Compose, not K8S.

**Comment by mabumusa1** [comment]
Please tag me when you need reviews, I am interested in this task

**Comment by francoisauclair911** [comment]
@jbmolle  & @wget  would you mind sharing your repos link so we can take a look ?
I think we can compare all "existing" solutions people came up with so we can grab ideas from all of them and merge them into one.

**Comment by jbmolle** [comment]
@francoisauclair911 I've set up a Github repo with my Dockerfile and Helm chart.
I still have to improve the size of the Docker Image.
For now I also haven't managed to have Redis in Mautic. The config works and all but it seems that Mautic is not using my Redis instance for caching.
https://github.com/jbmolle/mautic-k8s

**Comment by bigbeka** [comment]
I will be happy to contribute to the documentation for Docker Image, setup, config and so on.

**Comment by hcross** [comment]
I'm in and would be pleased to contribute !
Already setup a repository to get multiarch builds on mautic3 and 4 using Github Actions : https://github.com/hcross/docker-mautic/tree/mautic4

**Comment by RCheesley** [comment]
Hi folks!

I would love us to get this moving forward - it sounds like we have a great team of people who are willing to help with bringing Docker up to scratch and becoming a first-class citizen!

If you are not there already, please join us in #docker on Slack (get an invite at https://mau.tc/slack-invite to join the instance).

Let's bring everyone together who wants to be a part of this, figure out what tasks we need to prioritise and get things rolling. 

Let's set up a time to meet with the Product Team Lead @mollux when he's back from vacation (I think he is back on Wednesday, perhaps)! 🌴

**Comment by mollux** [comment]
Hi all, 

I merged https://github.com/mautic/docker-mautic/pull/238 yesterday, and the Mautic 5 images are available on https://hub.docker.com/r/mautic/mautic.

So IMO this issue can be closed.
If you have ideas to enhance on work on this, please create issues or PR's to make the containerized hosting of Mautic better.
