### ISSUE TITLE
sudo in mautic5

### ISSUE THREAD

**Issue by lordimac** [mautic/docker-mautic#254]
Hello, is sudo missing in mautic5 container or am I missing somehting? When clearing cache I can only use root, which sets the cache/prod folder to root permissions.

**Comment by mollux** [comment]
@lordimac 

thanks for raising the issue.
sudo isn't missing in the image :)
But it's indeed not documented how to execute commands like e.g. `php ./bin/console cache:clear`

I created [a PR](https://github.com/mautic/docker-mautic/pull/259) to add this to the readme, which you can review here: https://github.com/mautic/docker-mautic/blob/04b91d86a81093873616f2e75b26a88caeea0999/README.md#running-console-commands-with-docker-compose

can you check and confirm this allows you to clear the cache without running into file permission issues?

**Comment by lordimac** [comment]
Thank you! I didnt even think about running this command through docker. Also runs without "compose" if you used another stack management tool (like dockge).

**Comment by mollux** [comment]
thanks! closing this issue and merging the referenced PR
