### ISSUE TITLE
Cannot set SMTP configuration in Mautic 5

### ISSUE THREAD

**Issue by devilmind81** [mautic/docker-mautic#258]
How can I configure Gmail SMTP or another one for sending an email in the mautic 5?
There'isn't an option like the Mautic 4 one.
Thanks in advance

**Comment by RCheesley** [comment]
Hi @devilmind81, please read the documentation for Mautic 5: https://docs.mautic.org/en/5.x/configuration/settings.html#email-settings. It's all detailed there.

Please post at https://forum.mautic.org if you need any further support with this, thanks!

**Comment by devilmind81** [comment]
Thanks a lot!
