### ISSUE TITLE
Queue for failures using RabbitMQ

### ISSUE THREAD

**Issue by acremonezi** [mautic/docker-mautic#260]
Mautic: v5.0.3

Please, into this documentation bellow it is showing how to setup **Queue for failures** using the **Doctrine transport**.
https://docs.mautic.org/en/5.x/configuration/settings.html#queue-for-failures

But please, is it possible to setup **Queue for failures** using **RabbitMQ** as it is done for **Queue for email** and **Queue for hits**?
If so, Please, How?

Thanks in advanced.

**Comment by RCheesley** [comment]
Hi @acremonezi - would you mind posting this in https://forum.mautic.org as you're more likely to get some feedback there - we try to keep GitHub issues for bugs and tasks rather than support. Thanks!
