### ISSUE TITLE
Update 5.0.4

### ISSUE THREAD

**Issue by lordimac** [mautic/docker-mautic#273]
Hello, do we need to build an own image/wait for new image for mautic 5.0.4 or can we run web updater or composer updater?

**Comment by lordimac** [comment]
So far, tried the web updater after taking a backup. The task "Moving Package Contents" is running forever. Looks like we cant use the web updater with docker at the moment or the process is unclear.

**Comment by d-sushko** [comment]
same here, had to restore from backup after running mautic:update:apply --finish

**Comment by escopecz** [comment]
Am I missing something? I can see the images for 5.0.4 at https://hub.docker.com/r/mautic/mautic/tags
![Screenshot 2024-05-10 at 22 07 31](https://github.com/mautic/docker-mautic/assets/1235442/8799a081-ed96-4665-b5ac-5a8e9a40bf34)

**Comment by lordimac** [comment]
Yes, but when we openes this case it was not released. And the question will still be the same after the next update. Its more then a general question the a bug, but for the next update we should know if we can update mautic ourselfes without or with building an custom image.

**Comment by escopecz** [comment]
Gotcha. It depends how you deploy it. Do you use just one of the docker files or some of the Docker Compose examples? You shouldn't build your images unless you have a reason for it. The images already contain updated version of Mautic so no Composer nor manually via UI. Just spin up the new image.

**Comment by escopecz** [comment]
Yep, for that you'll need to build your own image.

**Comment by lordimac** [comment]
Thank you for the clarification. :)

**Comment by melakhvision** [comment]
Any way to solve this error. It's the command to perform an update is not yet supported to the version 5.x
```bash
mautic.ERROR: UPDATE CHECK: Could not fetch a release list: 403 (rate limit exceeded
```
