### ISSUE TITLE
Mautic doesn't accept requests to port 443

### ISSUE THREAD

**Issue by winers1290** [mautic/docker-mautic#28]
Unsure if this is by design or not, but when I proxy an https:// request to port 443 on the Mautic container, the container refuses the connection.

However, when I proxy an https:// request to port 80, it accepts it.

Guessing the Apache instance is not setup to open 443?

**Comment by Gregy** [comment]
I don't understand what are you trying to achieve. If you are attempting ssl termination see the example at https://github.com/mautic/docker-mautic/tree/master/examples/mautic-example-nginx-ssl

**Comment by winers1290** [comment]
Yes, and as per that document, only port 80 on the Mautic container is exposed. 

It's pure convention to have SSL connect to port 443, and I only raise it as an issue because I had been trying to terminate to 443 and could not figure out what was going wrong.

Is it not just a bit weird to have to go reverse_proxy:443 => Mautic:80 for an SSL connection? Maybe I'm complicating things.

**Comment by Gregy** [comment]
The ssl connection is terminated by nginx and the traffic from nginx to mautic is unencrypted. That is why it is using port 80.

**Comment by winers1290** [comment]
I haven't tested this, but does that mean proxied SSLs are unsupported? https://www.nginx.com/resources/admin-guide/nginx-tcp-ssl-upstreams/

I think in order for this to work, the Mautic container would need a setting to require client certificates.

**Comment by Gregy** [comment]
Yes. That configuration is currently not supported however we are accepting pull requests :)
