### ISSUE TITLE
Amazon SES on Mautic5 (docker-mautic image)

### ISSUE THREAD

**Issue by sauloroncon** [mautic/docker-mautic#282]
I was trying to use Amazon SES in mautic after migration for v5, but i got just a smtp config and it don't work properly for Amazon SES. There is a reason to take off this pre prepared types like Amazon SES, SendGrid, and others ?

**Comment by RCheesley** [comment]
Hi there, from Mautic 5.0 the email system has entirely changed. You can read the release notes here: 

https://github.com/mautic/mautic/releases/tag/5.0.0

Blog post here: https://www.mautic.org/blog/community/mautic-5-beyond-expectations-beyond-limits

Docs on email transports here: https://docs.mautic.org/en/5.x/configuration/settings.html#email-settings
