### ISSUE TITLE
View Report - Visits published Pages  show ip address as 127.0.0.1

### ISSUE THREAD

**Issue by hoanbc** [mautic/docker-mautic#288]
Hi everyone,
I have issue with ip address on "View Report - Visits published Pages". As the picture below it show is localhost (127.0.0.1). I running mautic version 5.1(nginx-fpm) on docker environment. I did add x-forward-for and x-real-ip but not resolve my problem. So someone know how to add real ip of customer into report? Please help me. Thank!
![image](https://github.com/mautic/docker-mautic/assets/26288807/f59527dd-8e69-496a-9e2d-f6c6d119e3db)

**Comment by farshadff** [comment]
any update for your problem ? i have the same

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems like this with configuration of Mautic. :)
