### ISSUE TITLE
Mautic reinstall from the beginning on every docker run

### ISSUE THREAD

**Issue by dmelo** [mautic/docker-mautic#31]
The first time I run the Mautic container, I configure the database on the Web interface and start using Mautic. If I kill the container and run a new one, connected to the same database, I expect it to continue from where it had stopped. Instead it redirects to the install page again. Docker containers are ephemeral by nature, we should be able to kill and run a new one without any additional effort or data loss.

I might be doing something wrong, in which case it would be very nice if someone would point me to the right direction.

Here are the steps to reproduce the behavior:

```
docker run --name some-mysql -e MYSQL_ROOT_PASSWORD=my-secret-pw mysql
docker run --rm --name some-mautic -p 8005:80 --link some-mysql:mysql mautic/mautic
```

Configure everything and install Mautic accessing http://localhost:8005 . Then kill the mautic `some-mautic` container and run it again:

```
docker run --rm --name some-mautic -p 8005:80 --link some-mysql:mysql mautic/mautic
```

You will see that you will be back on the "Install Mautic" page.

If you also think that it would be desirable to have the Mautic Docker image being able to persist its state from one container to another, I write this feature and make a PR.

**Comment by luizeof** [comment]
You need to create persistent docker volumes ...

**Comment by dmelo** [comment]
Thanks @luizof . Which paths should I transform into volumes? I tried creating a volume for the config path but didn't change much.

**Comment by dmelo** [comment]
OK. I saw that the Dockerfile is declaring /var/www/html as a volume. I have updated my docker-compose.yml to work with that.
