### ISSUE TITLE
Docker image only partially installs DB schema

### ISSUE THREAD

**Issue by mogul** [mautic/docker-mautic#39]
TL;DR: When you run the Docker commands to start the official Mautic image as a container, the resulting Mautic **looks** OK, but it turns out it's still missing 8 schema migrations. To allow them to proceed, you have to `DROP TABLE `mautic`.`email_stat_replies`;` then do `php app/console doctrine:migration:migrate`

I can't describe the details better than I did in [this Slack thread](https://mautic.slack.com/archives/C02HU8BUT/p1513278988000450).

**Comment by dbhurley** [comment]
Thanks for this. Definitely something that needs fixing!

**Comment by mogul** [comment]
Great, glad I could help. (Now if only I could see any hits from my tests in an Incognito browser I'd be golden.)

**Comment by Gregy** [comment]
I believe this is a problem in core mautic. I installed from mautic/mautic:master without the docker image and got the same result.

**Comment by luizeof** [comment]
Fixed on https://github.com/mautic/mautic/pull/5555
