### ISSUE TITLE
Setup cron jobs

### ISSUE THREAD

**Issue by ahansson89** [mautic/docker-mautic#4]
Can we add cron jobs for smart lists and other standard Mautic cron jobs for this image? Alternatively we could make an example of how to link a container managing cron jobs like the Tutum cron image: https://github.com/sillelien/tutum-cron

Let me know what you think and I can make a PR to the documentation.

**Comment by ahansson89** [comment]
Ideally I think it should be put in an environment variable

**Comment by tanzaho** [comment]
I think this could indeed be a great addition to the container

**Comment by ndarilek** [comment]
A simpler solution might be something like:

```
while true; do
  # Cron jobs here
  sleep 900
done
```

Disclaimer: I'm terrible at bash scripting.

Granted it doesn't handle failures well, but you don't really have many options for handling failures in containers other than complaining loudly and hoping someone is watching logs.

If there's interest in this route then I can submit a PR.

**Comment by optimum-web** [comment]
Another approach setup cron on a host machine and put something like this
*/5 * * * * user  docker exec mautic_container_1 app/console mautic:segments:rebuild --env=prod
*/5 * * * * user  docker exec mautic_container_1 app/console mautic:campaigns:rebuild --env=prod
...

**Comment by Gregy** [comment]
Thank you for the report. Sorry it took so long. Latest container includes cron, please give it a try.

**Comment by Jonbj** [comment]
Sorry for bother you, but i installed mautic con Rancher, and my cron doesn't run.
I set MAUTIC_RUN_CRON_JOBS=true, I can see the file mautic under /etc/crond.d/mautic but cron doesn't start and the command:
`crontab -l `
give:
`no crontab for root`
Also 
`crontab -u www-data -l`
give 
`no crontab for www-data`
Can you help me?

**Comment by hezll** [comment]
> Sorry for bother you, but i installed mautic con Rancher, and my cron doesn't run.
> I set MAUTIC_RUN_CRON_JOBS=true, I can see the file mautic under /etc/crond.d/mautic but cron doesn't start and the command:
> `crontab -l `
> give:
> `no crontab for root`
> Also
> `crontab -u www-data -l`
> give
> `no crontab for www-data`
> Can you help me?

 */5 * * * *     www-data   php /var/www/html/bin/console mautic:segments:update > /var/log/cron.pipe 2>&1
to  */5 * * * *     www-data   php /var/www/html/app/console mautic:segments:update > /var/log/cron.pipe 2>&1

Don't know why, but in my case, the program is under app not bin. That's why the docker cronjob can not run.
Please ensure you can manually run php /var/www/html/bin/console mautic:segments:update  in your docker
