### ISSUE TITLE
Hangs when amazon IMAP settings are added to the Default Mailbox

### ISSUE THREAD

**Issue by xtjoeywx** [mautic/docker-mautic#43]
When I add my Amazon SES IMAP settings, specifically the password to the Monitored Inbox Settings Default Mailbox then click the "Test connection and fetch folders" button it will come back saying the information is not correct. I repeated this a few more times to make sure my information was correct and it still said the same thing. The information I was entering is the exact same information I entered in the "Mail Send Settings" area at the top of the page. The tests are successful there.

What I mean by it "Hangs" is that it started to hang after a few times of re-entering my information in the Default Mailbox area and either clicking the test button or the page's apply button. After entering my information over and over again it eventually crashed and it gave me a "Database connection error (code #[0])". I waited a while and that error persisted. To fix it, I tried deleting the cache first and nothing. I then rebooted my server and restarted all of the docker containers. It is now back up and running, but it still hangs for a decent amount of time when I save the configuration page. I don't dare to enter any more information in the Default Mailbox area again. Mail is still sending, but I'm not sure if the Default Mailbox is going to work or not.

Is this a Mautic problem or is this because of Docker somehow?

**Comment by luizeof** [comment]
I hope that is an Mautic problem

2.12.2 has some fixes on Settings Page

**Comment by luizeof** [comment]
@xtjoeywx can you close this issue if problem was resolved please?

**Comment by xtjoeywx** [comment]
I’ve not been able to test it recently. To my knowledge, I don’t think it ever worked. I hope others have had success with it though. I don’t have time in the near future to try it. I’ll close this still though. Thanks.
