### ISSUE TITLE
Unable to connect with TLS encryption when using custom smtp as dockerized hardware/mailserver

### ISSUE THREAD

**Issue by goq** [mautic/docker-mautic#59]
I use dockerized hardware/mailserver for mail purposes. 
Can't setup e-mail settings in dockerized mautic: then i set smtp as custom TLS to 587 port (internal address use, or external - doesn't matter) - there are error "Unable to connect with TLS encryption"
All log here:
`Unable to connect with TLS encryption Log data: ++ Starting Swift_SmtpTransport << 220 mail.myserver.com ESMTP Postfix >> EHLO email.mymautic.com << 250-mail.myserver.com 250-PIPELINING 250-SIZE 502400000 250-ETRN 250-STARTTLS 250-ENHANCEDSTATUSCODES 250-8BITMIME 250-DSN 250 SMTPUTF8 >> STARTTLS << 220 2.0.0 Ready to start TLS !! Unable to connect with TLS encryption (code: 0)
++ Starting Swift_SmtpTransport << 220 mail.myserver.com ESMTP Postfix >> EHLO email.mymautic.com << 250-mail.myserver.com 250-PIPELINING 250-SIZE 502400000 250-ETRN 250-STARTTLS 250-ENHANCEDSTATUSCODES 250-8BITMIME 250-DSN 250 SMTPUTF8 >> STARTTLS << 220 2.0.0 Ready to start TLS !! Unable to connect with TLS encryption (code: 0)`

**Comment by goq** [comment]
My bad. Everything is ok. Sorry. 
All services works perfectly!

**Comment by dioneiserino** [comment]
@goq I have the same issue. 
Can you tell what was your fault please?

**Comment by panchtatvam** [comment]
I'm facing the same isssue. Mautic seems to work with SSL (465) but not with TLS(587).

**Comment by aiac** [comment]
Hello! It took couple of hours to investigate that, but finally I found issue. In my case it was TLS version constant with PHP 7.1. It changed on versions 5.6 above.

Try changing `STREAM_CRYPTO_METHOD_TLS_CLIENT` to `STREAM_CRYPTO_METHOD_TLSv1_2_CLIENT` (or other version) in _/mautic/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php_

**Comment by FMSGiganti** [comment]
@aiac Thanks a lot ! To me finally it works in PHP 7.3 with this change.
