### ISSUE TITLE
Campaign is not sending to all contacts in segment

### ISSUE THREAD

**Issue by xtjoeywx** [mautic/docker-mautic#63]
Problem:
Only 19 out of 300 new contacts received a campaign email. It seems to hang or stop.

Using:
Mautic v2.14.0
Digital Ocean - Ubuntu 16.4 LTS
Docker/Docker Compose
(Also tested this in a Kubernetes cluster)

Steps to recreate the problem:
1.) Create a segment with a tag.
2.) Create a template email.
3.) Create a campaign that pulls the above segment and instantly sends the above email.
4.) Import 300 contacts with that specific tag.
5.) Let mautic do its thing. You will see that the contacts will be added to the campaign. Then it will say that 100% of the contacts have received the email, BUT then if you go to the email page you'll see that only a smaller percentage as actually been sent that email. In my case 19 of the 300 contacts.
(see images below)
<img width="390" alt="email_page_stats" src="https://user-images.githubusercontent.com/35076109/44599356-44235f00-a793-11e8-9cc4-c96dd5b8a2f8.png">
<img width="667" alt="campaign_page_stats" src="https://user-images.githubusercontent.com/35076109/44599357-44235f00-a793-11e8-960a-87959dab4417.png">

**Comment by luizeof** [comment]
Hi @xtjoeywx this bug is related to Mautic itself.

Mautic 2.14.1 will fix this. For more info please see this pull request https://github.com/mautic/mautic/issues/6419

**Comment by luizeof** [comment]
Closing ;)

**Comment by YosuCadilla** [comment]
I tested with 2.14.1-beta and it seems NOT to solve the issue, here's a complete list of possibly related issues: #6515 #5546 #6482 #6419 #6211 #6433 #63

Seems Github has issues to solve too: #63 as seen here: mautic/docker-mautic#63

**Comment by YosuCadilla** [comment]
#6460 too probably.

**Comment by jqvanet** [comment]
I'm having the same issue and I don't use the action "Modify contact's segments".
I have 3 conditions testing a field value and 3 corresponding "Send email" actions.

Please help.
