### ISSUE TITLE
Database not migrate

### ISSUE THREAD

**Issue by dulabs** [mautic/docker-mautic#64]
I'm using composer below, database is created but the table  not generated.

`
mautic:
  image: mautic/mautic
  links:
    - mauticdb:mysql
  ports:
    - 8080:80

mauticdb:
  image: mysql:5.6
  environment:
    MYSQL_ROOT_PASSWORD: example
`

Output
`[CRON] [PDOException]
mautic_1    | [CRON] SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mautic.lead_lists' doesn't exist`

**Comment by luizeof** [comment]
Can you paste the entire log here please ?

Thanks !

**Comment by dulabs** [comment]
I see in docker-entrypoint no command mautic:install.

So after create config, it need to visit mautic url to do installation.

Thanks.
