### ISSUE TITLE
How to set PHP date.timezone setting?

### ISSUE THREAD

**Issue by jesseshieh** [mautic/docker-mautic#69]
The first time I accessed mautic, the installer recommended the following

> The date.timezone setting is not set in your PHP configuration. Mautic has set the default timezone to 'UTC' but we suggest setting this in your PHP configuration.

I looked for an environment variable or something, but didn't find anything. Is there some way to control the timezone?

**Comment by t-l-k** [comment]
Hey @jesseshieh , as I tackled this just last week, here was my solution:

Created the following file `mautic-php-timezone-en-gb.ini`, referencing the [list of PHP time zone constants](http://php.net/manual/en/timezones.php), and made it available in my Docker build context (which for me was adjacent my own `Dockerfile`):

```
date.timezone = Europe/London
```

Then in my `Dockerfile` which derives from `docker-mautic` as a base image, I added these lines:

```
COPY mautic-php-timezone-en-gb.ini /usr/local/etc/php/conf.d/
RUN chmod 755 /usr/local/etc/php/conf.d/mautic-php-timezone-en-gb.ini 
```

Et voila. 

I determined where best to place the .ini file by running `php --info` from a shell in the container.

**Comment by jesseshieh** [comment]
Thanks @t-l-k! I'll give that a try today. By the way, do you have any plans to open source your repository that has these fixes in it?

**Comment by t-l-k** [comment]
Hey @jesseshieh , I have forked the Mautic and Mautic-Docker repo but am layering additional Docker modifications in a seperate private repo at the moment as they're environment specific. When I've something PR worthy I'll raise it.
