### ISSUE TITLE
Container & SSL

### ISSUE THREAD

**Issue by dinchamion** [mautic/docker-mautic#7]
Hey,

I can run Mautic with SSL with an nginx-proxy, but I can't seem to figure out how to set up ssl for the container itself.

Without it, forms and such are still generated as http, and while the js is working through https, the generated connection is reported as insecure and throws errors in the browser console.

**Comment by jmeyo** [comment]
I stumble upon the same problem, as mautic is based on symfony, you need to configure trusted proxies. 
I didn't found where to set it in the mautic webui, so I just added it in my `app/config/local.php` file.

    $parameters = array(
      'db_driver' => 'pdo_mysql',
      # ... 

      'trusted_proxies'=>array('172.17.0.0/8')
    );

**Comment by RCheesley** [comment]
Thanks for this @jmeyo - I think we were having the same problem using our own docker image regarding SSL behind a proxy, so this may well have given a bit of a head start!  Will report back if it fixes the problems we're seeing!

**Comment by Gregy** [comment]
Hello,
thank you for the bug report. @jmeyo is correct, this behaviour is caused by the missing trusted_proxies. Please take a look at the new mautic-nginx-ssl example here: https://github.com/mautic/docker-mautic/tree/master/examples/mautic-example-nginx-ssl
