### ISSUE TITLE
2.15 is missing as a tag in docker images

### ISSUE THREAD

**Issue by rdxmb** [mautic/docker-mautic#82]
Hi, 
as the actual version (2.15) is missing as a docker tag - so manually updating with using tags in docker is not possible.

And, as in the docs

> Mautic Docker has two ENV that you can specify an version do start your new container:
>     -e MAUTIC_VERSION (Defaults to "2.15.0")

for sure? IMHO this should be 
'that you can specify an version do **build** your new container'

**Comment by jodumont** [comment]
also; the tag nginx don't exist

![image](https://user-images.githubusercontent.com/5204724/53721341-50cff080-3e63-11e9-94cf-8620224f874a.png)

**Comment by luizeof** [comment]
@jodumont thanks for this report. The correct tag is `fpm`.

**Comment by elwood218** [comment]
Why there is a tag for 2.13 then? Imho this is quite confusing. And using only apache is like using master branch. So I can only use 2.13 with php 7.0 where Mautic 2.13 is pinned as default.

**Comment by francis-ve** [comment]
@luizeof   2.14.* docker images are completely missing :(

**Comment by Unichron** [comment]
do you plan to upload at least the latest v2 image(s) to dockerhub?

**Comment by mollux** [comment]
I'm closing this issue as it concerns an old and unsupported version. 
If you think this issue is still relevant, please re-open it and specify why
