### ISSUE TITLE
Mautic on Docker does not seems to work

### ISSUE THREAD

**Issue by felipeplets** [mautic/docker-mautic#83]
I could not realize the source for the error but seems like Mautic docker master tag is not working and nor the instructions work. Also the listed tags exists (at least nginx). 

Which is the status for this project? Should it work? Is there someone actively maintaining it?

**Comment by tkima** [comment]
Ive tried it yesterday and it worked but had some issues with the volumes and the cache of composer on restart.

**Comment by tkima** [comment]
But the API was not working (error 404) with the docker. I could get a access_token but when i started to use it to get information it gave me a 404 error.

Everywhere you read about cleaning the cache. But if you do it on a docker or on a volume the ownership wil change again. So your the script gives you "current offline" window. 

How to fix the API on docker do the next steps (there are probably faster methods): 
1. Turn on the api in the control panel
2. Create oauth2 credentials in the control panel
3. Do a api test call to the api using composer mautic/api-library, you probably can get the access_token but can't get any info from the api (eg Looks like I encountered an error (error #404))
4. set memory_limit in php.ini to -1 (probably want to reset is to 256mb later on)
5. login to the docker: docker exec -it {dockerid} bash
6. clear the cache: php app/console cache:clear
7. set the user ownership to www-data again: chown -R www-data:www-data /var/www/html/

The mautic is still running and i can information from the api with the access_token.

**Comment by luizeof** [comment]
hi @felipeplets did you encounter a problem when running mautic docker? Are you using compose or are you running through the command line?

**Comment by aspiers** [comment]
@felipeplets It worked for me.  I'm afraid you are unlikely to receive help unless you give details of the problem you encountered.  Please see https://www.chiark.greenend.org.uk/~sgtatham/bugs.html

**Comment by felipeplets** [comment]
Hello @aspiers, thank you for the link.

Regarding the error I've faced I remember to get no feedback and specific error messages on docker logs, it was just running but I could not access it on the published port, so I could not realize the error or how to reproduce it. I've then installed and used it locally for my tests.
