### ISSUE TITLE
Own config cannot be mounted because of last commits

### ISSUE THREAD

**Issue by elwood218** [mautic/docker-mautic#88]
Because of recent changes it's not possible to put a paths_local.php or parameters_local.php via configMap-Mount because one new command in entrypoint is failing.
See my comment on: https://github.com/mautic/docker-mautic/commit/34214ccef25fea7b7c80d56baa7af6dbfdd50d36

**Comment by luizeof** [comment]
how can I reproduce this error?

**Comment by elwood218** [comment]
For example if you want to change the paths for mautic to make them persistent you need to change config via e.g parameters_local.php.
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: parameters-local
data:
  parameters_local.php: |
    <?php
    $parameters = array(
        'debug' => true,
        'image_path' => 'app/local/media/images',
        'upload_dir' => '%kernel.root_dir%/local/media/files',
        'mailer_spool_path' => '%kernel.root_dir%/local/spool',
        'cache_path' => '%kernel.root_dir%/local/cache'
    );
```
This will then be mounted in a kubernetes deployment.

```apiVersion: apps/v1
kind: StatefulSet
metadata:
...
spec:
...
    spec:
      containers:
      - env:
...
 
        image: mautic/mautic:apache
        imagePullPolicy: IfNotPresent
...
        volumeMounts:
        - mountPath: /var/www/html/app/config/paths_local.php
          name: paths-local-volume
          subPath: paths_local.php
        - mountPath: /var/www/html/app/config/parameters_local.php
          name: parameters-local-volume
          subPath: parameters_local.php
```

**Comment by elwood218** [comment]
I also don't see why this line was added? This wasn't necessary before so why this is needed now?

**Comment by elwood218** [comment]
@luizeof I am testing it and for my setup and can tell you next days hopefully

**Comment by elwood218** [comment]
@luizeof I was able to test it and my Helm Chart is working now again in my Kubernetes Cluster when removing that line. 
But at the moment I have build my own docker image because I cannot use tag `apache` because it is like master and every change could destroy my kubernetes deployment. I am missing a tag `2.15-apache`.

**Comment by luizeof** [comment]
@elwood218 Mautic runs within many scenarios ... this change solve some problems here .... but i'm rollback this commit and make this on my own image ;)

many thanks for the warning ;)

**Comment by luizeof** [comment]
@elwood218 can you test please?

**Comment by elwood218** [comment]
@luizeof to which docker tag is that master branched pushed? Can I use tag `apache` now?
But anyway there should be a docker tag `2.15-apache` so that no changes like that will effect an existing deployment. So using tag `apache` is like using `latest`.

**Comment by elwood218** [comment]
It seems like it is not yet pushed to docker hub.

Kubernetes describe on pod:
```Events:
  Type     Reason   Age                From               Message
  ----     ------   ----               ----               -------
  Normal   Pulling  34m (x13 over 1h)  kubelet, minikube  pulling image "mautic/mautic:apache"```

Kubernetes log on pod:
```Writing initial Mautic config

========================================================================
chown: changing ownership of '/var/www/html/app/config/paths_local.php': Read-only file system
chown: changing ownership of '/var/www/html/app/config/parameters_local.php': Read-only file system```

**Comment by luizeof** [comment]
@elwood218  can you try again please?

**Comment by elwood218** [comment]
@luizeof I have tested it now and it seems to work again. So we can close this ticket. Anyway I would recommend that there is another tag `2.15-apache` then it would not matter to make changes in tag `apache`.
