### ISSUE TITLE
Cannot access index_dev.php

### ISSUE THREAD

**Issue by arashsoheili** [mautic/docker-mautic#89]
When trying to access http://localhost:8080/index_dev.php get a You are not allowed to access this file. Tried to set dev_hosts in config local.php to localhost and also internal container ip but not luck. Any suggestions or fix?

**Comment by luizeof** [comment]
@escopecz Mautic Dev need some tweak to run?

**Comment by escopecz** [comment]
If you look how Mautic is being installed [in the docker file](https://github.com/mautic/docker-mautic/blob/master/apache/Dockerfile#L47) then you see that it downloads the production zip package. This package contains all libraries but it doesn't include dev dependencies. 

So, if you want Mautic to have the developer dependencies then use the raw version from github and install all dependencies with Composer.

**Comment by ebrake** [comment]
In case other people run into this, you can disabled the ip check directly in `app/middlewares/Dev/IpRestrictMiddleware.php`

**Comment by nest-don** [comment]
Add your public IP in app/config/dev_hosts array.  This will enable access to this file.
