### ISSUE TITLE
Composer.json missing?

### ISSUE THREAD

**Issue by madmath03** [mautic/docker-mautic#95]
I might be missing something here so feel free to correct me, but I do not understand why composer is installed but Mautic composer.json and composer.lock are not added to the container.

What's point of having composer without the project's project file ?
I know those files are not present in the archive which is downloaded but I mostly wonder if there is a reason for not adding them or if it's a mistake that should be fixed.

**Comment by RCheesley** [comment]
Hi folks, I believe that this was fixed in Core, sorry that it wasn't reviewed here sooner. I'll close this PR down but feel free to reply if it's still relevant.
